# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chickendiseaseclassificationapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://chickendiseaseclassificationapp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_25667eb16e32447299bbf7f308928638 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c6be5abcbde848d1b5b10a5966474631 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: chickendiseaseclassificationapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_25667eb16e32447299bbf7f308928638 }}/chicken:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chickendiseaseclassificationapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_293a349cc42144e39fc8cfed1f589f0d }}
        images: 'chickendiseaseclassificationapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_25667eb16e32447299bbf7f308928638 }}/chicken:${{ github.sha }}'